### PR TITLE
Support big endian machines (trie file in BE)

### PR DESCRIPTION
**Pull request by liborm85**
Trie header part is write in big-endian and data part is write in little-endian on Intel x86 and big-endian on MIPS, s390x,... now.

This PR everything unifies and all is write in network byte order (alias big-endian). It does not matter machine endianity.
This is breaking change - content of trie file is different.

Fix for: https://github.com/foliojs/linebreak/issues/8

### CODE REVIEW

**Comment by blikblum** [comment]
This would add dependency on 'os' package which is node specific, making harder to run in browsers.

Also, by what i understand (may be wrong), projects that uses unicode-trie, like linebreak already runs in every system. The problem is only if the trie file is regenerated on big endian machines which IMO is just an annoyance, not worth the trouble the extra code / dependency.

**Comment by devongovett** [comment]
Did you look into using Dataview to read and write from the arraybuffer? I believe it supports both little and big endian and is built into both node and browsers.

**Comment by liborm85** [comment]
@blikblum

> This would add dependency on 'os' package which is node specific, making harder to run in browsers.

I rewrote it without using os.

> Also, by what i understand (may be wrong), projects that uses unicode-trie, like linebreak already runs in every system. The problem is only if the trie file is regenerated on big endian machines which IMO is just an annoyance, not worth the trouble the extra code / dependency.

No, it's more complicated.
For example: linebreak library published on npm have generated trie on little-endian machine (probably MacOS) and works only on little-endian machines; not work on big-endian (see https://github.com/foliojs/linebreak/issues/8). If is trie generated on big-endian machine it works only on big-endian machine. It is never compatible for both endian machines.


@devongovett

> Did you look into using Dataview to read and write from the arraybuffer? I believe it supports both little and big endian and is built into both node and browsers.

For use DataView more code changes is needed. I'll try to explore and rewrite it.

**Comment by liborm85** [comment]
PR test output:
```
  unicode trie
    √ set
    √ set -> compacted trie
    √ setRange
    √ setRange -> compacted trie
    √ should work with compressed serialization format (57ms)
    √ should pass range tests (389ms)


  6 passing (523ms)
```

**Comment by liborm85** [comment]
@devongovett I create new PR https://github.com/foliojs/unicode-trie/pull/6 with implementation via DataView.
I didn't do stress tests directly, but in unit tests implementation via Uint32Array and switch bytes (this PR) running [523 ms](https://github.com/foliojs/unicode-trie/pull/5#issuecomment-503625400) and implementation via DataView (PR https://github.com/foliojs/unicode-trie/pull/6) running [982 ms](https://github.com/foliojs/unicode-trie/pull/6#issuecomment-503625202) on my notebook.

Implementation via DataView is much slower.
I think it better to use this first implementation because it is faster, but I leave the decision to you.

cc @blikblum

**Comment by blikblum** [comment]
I would go for faster one, but have no hard opinion

**Comment by devongovett** [comment]
Interesting! That’s somewhat surprising. I’m fine with the faster option.

Another (a little non standard) option could be to store it in little endian and only swap on big endian machines. Should be faster since most machines are little endian these days...

**Comment by blikblum** [comment]
> Another (a little non standard) option could be to store it in little endian and only swap on big endian machines. Should be faster since most machines are little endian these days...

Seems better

**Comment by liborm85** [comment]
Trie header was originally written in big-endian, and according to https://en.wikipedia.org/wiki/Endianness is standard "network byte order" is big-endian, true it is for networks, not files (but for example PNG is in big-endian - [stackoverflow.com](https://stackoverflow.com/questions/2384111/png-file-format-endianness/2384128#2384128)). These are two reasons why I used big-endian. But it can be changed.

Change PR to write as little-endian?

**Comment by blikblum** [comment]
> Change PR to write as little-endian?


By my side, yes

**Comment by liborm85** [comment]
I'll prepare it on weekend.

**Comment by liborm85** [comment]
I create new PR https://github.com/foliojs/unicode-trie/pull/8 with trie file format little-endian.

I run tests 30 times (for difference measurable) on my notebook (little-endian):
- big-endian format running 6007 ms (this PR)
- little-endian format running 5983 ms (PR https://github.com/foliojs/unicode-trie/pull/8)

The difference is only 24 ms.
There is no difference for performance, therefore in my opinion is better to use network order standard (big-endian). @devongovett I leave the decision to you, two PRs ready.

**Comment by blikblum** [comment]
I would create a simple script using performance.now() to measure the performance instead of running the tests since most of the time will be spend in the testing stack

Also consider the suggestion i did on other PR

**Comment by liborm85** [comment]
Changed in both PRs.

**Comment by liborm85** [comment]
Simple performance test for opening trie file:

```js
const { performance } = require('perf_hooks');
const UnicodeTrie = require('unicode-trie');
const fs = require('fs');

const runTest = () => {
  const iterationCount = 10000;
  let start = performance.now();
  const data = fs.readFileSync('src/classes.trie');
  for (let i = 0; i < iterationCount; i++) {
    const trie = new UnicodeTrie(data);
  }
  console.log(performance.now() - start, 'ms');
}

runTest();
```
(File `src/classes.trie` used from [linebreak](https://github.com/foliojs/linebreak))

Results time jump a lot...
Average time of results:
- big-endian: 3175 ms
- little-endian: 2953 ms

**Comment by liborm85** [comment]
In class `UnicodeTrieBuilder` method `toBuffer` is same swap over same array as in opening therefore time should be the same.

**Comment by blikblum** [comment]
I would go with trie file in BE

**Comment by liborm85** [comment]
@devongovett 
I could merge it myself but I don't have permission to publish in npm. Could you do it @devongovett?

**Comment by blikblum** [comment]
Sorry about misleading comment above. Somehow i got confused. For me, i would go with file in LE.

**Comment by devongovett** [comment]
Closing in favor of #8.

**Pull request closed without merging**
